### ISSUE TITLE
`s_block()` returns AttributeError

### ISSUE THREAD

**Issue by joswr1ght** [jtpereyda/boofuzz#163]
Using`s_block()` returns an AttributeError:

```
PS ...> python -c 'import boofuzz; print boofuzz.__version__'
0.0.9
PS ...> Get-Content .\boofuzz1.py
from boofuzz import *

with s_block("main"):
  s_string("GET /index.html")
PS ...> python -V
Python 2.7.12
PS ...> python .\boofuzz1.py
Traceback (most recent call last):
  File ".\boofuzz1.py", line 3, in <module>
    with s_block("main"):
  File "C:\Python27\lib\site-packages\boofuzz\__init__.py", line 173, in s_block
    block = s_block_start(name, group, encoder, dep, dep_value, dep_values, dep_compare)
  File "C:\Python27\lib\site-packages\boofuzz\__init__.py", line 193, in s_block_start
    blocks.CURRENT.push(block)
AttributeError: 'NoneType' object has no attribute 'push'
```

This is almost certainly low priority since `s_block()` is just used for pretty indentation, but FYI.

**Comment by joswr1ght** [comment]
Sorry, my mistake. Sulley didn't formerly require `s_initialize()`, but Boofuzz does. Noted. Thanks!
