### ISSUE TITLE
s_string cannot accept unicode

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#178]
This error came from sending a normal ASCII string but with type unicode rather than bytes:
```
Traceback (most recent call last):
  File "ftp.py", line 60, in <module>
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "ftp.py", line 33, in fuzz
    s_string(password)
  File "/home/jtpereyda/boofuzz/boofuzz/__init__.py", line 487, in s_string
    s = primitives.String(value, size, padding, encoding, fuzzable, max_len, name)
  File "/home/jtpereyda/boofuzz/boofuzz/primitives/string.py", line 49, in __init__
    self._value * 2 + "\xfe",
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfe in position 0: ordinal not in range(128)
```

**Comment by aedrax** [comment]
is this still a bug?

**Comment by NRDeshpande** [comment]
@aedrax 
Yes, getting the same error.

`  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 1431, in _fuzz_current_case
    self.transmit_fuzz(target, self.fuzz_node, path[-1], callback_data=callback_data)
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 1114, in transmit_fuzz
    self.targets[0].send(data)
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 157, in send
    self._fuzz_data_logger.log_send(data[:num_sent])
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/fuzz_logger.py", line 71, in log_send
    fuzz_logger.log_send(data=data)
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/fuzz_logger_csv.py", line 59, in log_send
    self._print_log_msg(["send", len(data), self._format_raw_bytes(data), data.decode()])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfe in position 18: ordinal not in range(128)
`

**Comment by aedrax** [comment]
if you're using the `s_string` and you want to use another encoding you just have to specify it, correct?
for example
`s_string("฿", encoding="utf-8")`

**Comment by SR4ven** [comment]
I just tried to reproduce this error, but everything work perfectly fine.
Running the ftp example and some unicode strings on Python 2.7 and 3.7 didn't throw any exceptions.

However, if this problem still persists, please comment/reopen.
