### ISSUE TITLE
Crash when starting process_monitor.py

### ISSUE THREAD

**Issue by andreascla** [jtpereyda/boofuzz#207]
I tried to use process_monitor.py on a Windows XP host while fuzzing from a Kali Linux machine. The process monitor seems to crash when it's looking for a crashbin file that doesn't exist. This is the first time the fuzzer is running so obviously there is no crashbin file written to disk yet.

```
Traceback (most recent call last):
  File "C:\Users\Andreas\Downloads\boofuzz\process_monitor.py", line 45, in <module>
    go()
  File "C:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Andreas\Downloads\boofuzz\process_monitor.py", line 40, in go
    log_level=log_level,
  File "C:\Users\Andreas\Downloads\boofuzz\process_monitor.py", line 14, in serve_procmon
    servlet.serve_forever()
  File "C:\Users\Andreas\Downloads\boofuzz\boofuzz\pedrpc.py", line 284, in serve_forever
    ret = method(*args, **kwargs)
  File "C:\Users\Andreas\Downloads\boofuzz\boofuzz\utils\process_monitor_pedrpc_server.py", line 139, in pre_send
    self.debugger_thread.pre_send()
  File "C:\Users\Andreas\Downloads\boofuzz\boofuzz\utils\debugger_thread_pydbg.py", line 169, in pre_send
    self.process_monitor.crash_bin.import_file(self.process_monitor.crash_filename)
  File "C:\Users\Andreas\Downloads\boofuzz\boofuzz\utils\crash_binning.py", line 219, in import_file
    fh  = open(file_name, "rb")
IOError: [Errno 2] No such file or directory: u'C:\\tools\\vulnserver\\vulnserver.crashbin'
```

After a bit of research in the old Sulley code I found a try/except pair that is not present in the boofuzz code. Testing with the following change in `boofuzz/boofuzz/utils/debugger_thread_pydbg.py`fixes the problem:

```
def pre_send(self):
    # un-serialize the crash bin from disk. this ensures we have the latest copy (ie: vmware image is cycling).
    try:
        self.process_monitor.crash_bin.import_file(self.process_monitor.crash_filename)
    except:
        pass
```

However, I'm not sure that the `except: pass` is a good solution so maybe it should be solved in another way?

Apologies for being new on GitHub, let me know if I should do a pull/merge request or similar and fix it myself, I'm happy to contribute :-)

**Comment by jtpereyda** [comment]
@andreascla Thank you for the thorough and clear bug report! I haven't had a chance to test this myself, but I think you are on the whole correct. I likely removed this without sufficient testing; if that is the case, it was because of the overly general `except: pass`. If you are interested in fixing yourself, I would recommend starting with:
```python
except IOError:
    pass  # ignore missing file, etc.
```

**Comment by jtpereyda** [comment]
Pull requests always welcome : )

**Comment by andreascla** [comment]
@jtpereyda Thanks for feedback, I will investigate some more and send a fix eventually :)
