### ISSUE TITLE
help me boofuzz Target is not connected

### ISSUE THREAD

**Issue by 527641718** [jtpereyda/boofuzz#219]
```
C:\Users\Administrator>python C:\Users\Administrator\Desktop\examples\ftp-with-p
rocmon.py
[2018-11-13 13:28:20,126] Test Case: 1: user.no-name.1
[2018-11-13 13:28:20,130]     Info: Type: String. Default value: 'USER'. Case 1
of 11716 overall.
[2018-11-13 13:28:20,139]   Test Step: Calling procmon pre_send()
[2018-11-13 13:28:20,194]     Info: Opening target connection (127.0.0.1:21)...
[2018-11-13 13:28:20,199]     Info: Connection opened.
[2018-11-13 13:28:20,204]   Test Step: Fuzzing Node 'user'
[2018-11-13 13:28:20,213]     Transmitting 8 bytes: 20 61 64 6d 69 6e 0d 0a ' ad
min\r\n'
[2018-11-13 13:28:20,234]     Info: 8 bytes sent
[2018-11-13 13:28:20,239]     Info: Closing target connection...
[2018-11-13 13:28:20,243]     Info: Connection closed.
[2018-11-13 13:28:20,253]   Test Step: Contact process monitor
[2018-11-13 13:28:20,273]     Check: procmon.post_send()
```
process_monitor.py：
```
C:\Users\Administrator>python C:\Python27\Lib\site-packages\boofuzz\process_moni
tor.py -p  Ftpserver.exe
[01:27.57] Process Monitor PED-RPC server initialized:
[01:27.57]       listening on:  0.0.0.0:26002
[01:27.57]       crash file:    C:\Users\Administrator\boofuzz-crash-bin
[01:27.57]       # records:     0
[01:27.57]       proc name:     Ftpserver.exe
[01:27.57]       log level:     1
[01:27.57] awaiting requests...
[01:28.20] Starting target...
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\boofuzz\process_monitor.py", line 45, in <
module>
    go()
  File "C:\Python27\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\boofuzz\process_monitor.py", line 40, in g
o
    log_level=log_level,
  File "C:\Python27\Lib\site-packages\boofuzz\process_monitor.py", line 14, in s
erve_procmon
    servlet.serve_forever()
  File "C:\Python27\lib\site-packages\boofuzz\pedrpc.py", line 284, in serve_for
ever
    ret = method(*args, **kwargs)
  File "C:\Python27\lib\site-packages\boofuzz\utils\process_monitor_pedrpc_serve
r.py", line 138, in pre_send
    self.start_target()
  File "C:\Python27\lib\site-packages\boofuzz\utils\process_monitor_pedrpc_serve
r.py", line 151, in start_target
    coredump_dir=self.coredump_dir)
TypeError: __init__() got an unexpected keyword argument 'coredump_dir'
```

**Comment by omaidf** [comment]
I have the same issue.

**Comment by 527641718** [comment]
> 我有同样的问题。

I modified debug_thread_pydbg.py's def __init__(self, start_commands, process_monitor, proc_name=None, ignore_pid=None, pid=None, log_level=1, coredump_dir=None): post prompt
> python C:\boofuzz-0.1.1\process_monitor.py -p FTPserver.exe
[02:39.15] Process Monitor PED-RPC server initialized:
[02:39.15]       listening on:  0.0.0.0:26002
[02:39.15]       crash file:    C:\Users\Administrator\Desktop\boofuzz-crash-bin
[02:39.15]       # records:     0
[02:39.15]       proc name:     FTPserver.exe
[02:39.15]       log level:     1
[02:39.15] awaiting requests...
[02:39.20] Starting target...
[02:39.20] starting target process
[02:39.20] done. target up and running, giving it 5 seconds to settle in.
Exception in thread 1542263960:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\boofuzz-0.1.1\boofuzz\utils\debugger_thread_pydbg.py", line 117, in run
    self.spawn_target()
  File "C:\boofuzz-0.1.1\boofuzz\utils\debugger_thread_pydbg.py", line 111, in spawn_target
    self.pid = self._process.pid
AttributeError: 'NoneType' object has no attribute 'pid'

**Comment by jtpereyda** [comment]
@527641718 @omaidf Thank you for the bug reports! I messed up a recent release and borked the Windows procmon. :( Should be working after PR #221 . If not, feel free to reopen. Thank you!

**Comment by KevinCooper** [comment]
This still looks to be an issue.  I get the following error 
```
  File "C:\Users\user\Desktop\boofuzz\boofuzz\pedrpc.py", line 284, in serve_forever  

    ret = method(*args, **kwargs)

  File "C:\Users\johna\Desktop\boofuzz\boofuzz\utils\process_monitor_pedrpc_server.py", line 138, in pre_send

    self.start_target()

  File "C:\Users\user\Desktop\boofuzz\boofuzz\utils\process_monitor_pedrpc_server.py", line 151, in start_target

    coredump_dir=self.coredump_dir)

TypeError: __init__() got an unexpected keyword argument 'coredump_dir'
```
