### ISSUE TITLE
Docs build failing

### ISSUE THREAD

**Issue by SR4ven** [jtpereyda/boofuzz#240]
I only just noticed that the docs build status is on failing and decited to have a look at it.
These are the errors I'm currently getting:
```
Running Sphinx v1.6.7
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [singlehtml]: all documents
updating environment: 0 added, 13 changed, 0 removed
reading sources... [100%] user/static-protocol-definition
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.sex.rst:4: WARNING: autodoc: failed to import module u'boofuzz.sex'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named sex
/home/raven/.local/lib/python2.7/site-packages/boofuzz/serial_connection.py:docstring of boofuzz.SerialConnection:32: WARNING: Unknown target name: "data".
/home/raven/Documents/git/boofuzz/docs/user/logging.rst:40: WARNING: autodoc: failed to import class u'FuzzLoggerFile' from module u'boofuzz'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 665, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 554, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/inspect.py", line 185, in safe_getattr
    raise AttributeError(name)
AttributeError: FuzzLoggerFile
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/raven/Documents/git/boofuzz/docs/source/boofuzz.event_hook.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.helpers.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.instrumentation.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.ip_constants.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.pedrpc.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.sex.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.utils.crash_binning.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/source/boofuzz.utils.dcerpc.rst: WARNING: document isn't included in any toctree
/home/raven/Documents/git/boofuzz/docs/user/contributing.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
assembling single document... user/install user/quickstart source/Session source/Target user/connections user/logging user/static-protocol-definition
writing... done
writing additional files...
copying images... [100%] _static/boo.png
copying static files... done
copying extra files... done
dumping object inventory... done
build succeeded, 12 warnings.
```

1. Can be fixed by removing `boofuzz/docs/source/boofuzz.sex.rst` as sex module doesn't exist anymore.
2. Related to `boofuzz/serial_connection.py` fixed itself for some reason after taking care of the other errors.
3. Adjust `boofuzz/docs/user/logging.rst` for `boofuzz.FuzzLoggerFile` as that class is depreciated. Might as well remove that class completely as it most likely won't even work in the current state.
4. `document isn't included in any toctree` is optimal but would be nice to have.

**Comment by jtpereyda** [comment]
@SR4ven Good catch! These fixes make sense. Eventually, it would be good to get the docs build into the CI build so that these can be caught on pull requests.

**Comment by SR4ven** [comment]
Adding the docs build to CI would be really nice indeed.
Are you going to apply the fixes from above yourself or do you want me to open a pull request?

**Comment by jtpereyda** [comment]
Feel free to open a PR -- my goal is to get through all the standing PRs this weekend, so I most likely won't get to this right away.
