### ISSUE TITLE
database is locked error

### ISSUE THREAD

**Issue by TheBull963** [jtpereyda/boofuzz#252]
When running a script utilizing boofuzz I get the following error when script is being run from a mounted drive. If I run the script from local drive, it runs fine. Permissions on mounted drive are fine, all other applications connect and use it without issue. I can place the script in a new folder with nothing else in it and get the same error.

Any suggestions? Here is the error

Traceback (most recent call last):
  File "httpfuzz.py", line 40, in <module>
    main()
  File "httpfuzz.py", line 8, in main
    connection=SocketConnection("192.168.10.10", 80, proto='tcp')
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/sessions.py", line 353, in __init__
    self._db_logger = fuzz_logger_db.FuzzLoggerDb(self._db_filename)
  File "/usr/local/lib/python2.7/dist-packages/boofuzz/fuzz_logger_db.py", line 39, in __init__
    self._db_cursor.execute('''CREATE TABLE cases (name text, number integer, timestamp TEXT)''')
sqlite3.OperationalError: database is locked

**Comment by jtpereyda** [comment]
@TheBull963 I did a little searching; the following links may be helpful:

1. https://stackoverflow.com/questions/907993/database-is-locked-error-in-sqlite-over-a-mac-network
1. https://github.com/docker/for-win/issues/11
