### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by starek4** [jtpereyda/boofuzz#296]
I use `SocketConnection` with `tcp` protocol.

When I run a bunch of tests, sometimes (for me usually after between 15 000 - 30 000 test cases) I got the following error:

```
Traceback (most recent call last):
  File "fuzzer/src/wfuzz.py", line 43, in <module>
    main()
  File "fuzzer/src/wfuzz.py", line 39, in main
    fuzzer.fuzz()
  File ".../fuzzer/src/fuzzer.py", line 52, in fuzz
    self._session.fuzz()
  File ".../env/lib/python3.6/site-packages/boofuzz/sessions.py", line 590, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File ".../env/lib/python3.6/site-packages/boofuzz/sessions.py", line 695, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File ".../env/lib/python3.6/site-packages/boofuzz/sessions.py", line 1412, in _fuzz_current_case
    self._open_connection_keep_trying(target)
  File ".../env/lib/python3.6/site-packages/boofuzz/sessions.py", line 1450, in _open_connection_keep_trying
    target.open()
  File ".../env/lib/python3.6/site-packages/boofuzz/sessions.py", line 79, in open
    self._target_connection.open()
  File ".../env/lib/python3.6/site-packages/boofuzz/socket_connection.py", line 159, in open
    self._sock.connect((self.host, self.port))
OSError: [Errno 98] Address already in use
```

It happens on both Windows and WSL and different versions of Python. No other application is connecting to the target port. Any ideas?

**Comment by starek4** [comment]
When I have both server and fuzzer on the same machine, everything works fine.

**Comment by starek4** [comment]
Well, after the weekend, I cannot reproduce this issue again. So I will believe that it was some environmental problem and hope that it never shows again. Closing this issue for now and when I see this behavior again, I will try to investigate it more and share with you guys what I've found.

**Comment by jtpereyda** [comment]
I think I've seen that sort of thing before, but it was also transient for me. I remember something about the OS sometimes holding onto TCP connections. Could also be another program that happened to be trying to use the same port.

It also depends on your configuration -- if you're simply connecting to another TCP server, this would be rather unexpected.

**Comment by starek4** [comment]
Well, it happens again 😢 

There is indeed a problem that TCP connections are not terminated. They are stuck in the state: **TimeWait**

You can see it here:
![Screenshot_1](https://user-images.githubusercontent.com/2153835/66515111-bd3c5d80-eade-11e9-86dd-1b24c2ab65d5.png)
and the list continues... until all port numbers are exhausted. 

Error message on WSL:
```
Traceback (most recent call last):
  File "fuzzer/src/wfuzz.py", line 43, in <module>
    main()
  File "fuzzer/src/wfuzz.py", line 39, in main
    fuzzer.fuzz()
  File "[...]/Desktop/harbor_new/fuzzer/src/fuzzer.py", line 71, in fuzz
    self._session.fuzz()
  File "[...]/Desktop/harbor_new/env/lib/python3.6/site-packages/boofuzz/sessions.py", line 608, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "[...]/Desktop/harbor_new/env/lib/python3.6/site-packages/boofuzz/sessions.py", line 714, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "[...]/Desktop/harbor_new/env/lib/python3.6/site-packages/boofuzz/sessions.py", line 1447, in _fuzz_current_case
    self._open_connection_keep_trying(target)
  File "[...]/Desktop/harbor_new/env/lib/python3.6/site-packages/boofuzz/sessions.py", line 1485, in _open_connection_keep_trying
    target.open()
  File "[...]/Desktop/harbor_new/env/lib/python3.6/site-packages/boofuzz/sessions.py", line 89, in open
    self._target_connection.open()
  File "[...]/Desktop/harbor_new/env/lib/python3.6/site-packages/boofuzz/socket_connection.py", line 169, in open
    self._sock.connect((self.host, self.port))
OSError: [Errno 98] Address already in use
```

Error message on WSL:
```
Traceback (most recent call last):
  File "./fuzzer/src/wfuzz.py", line 43, in <module>
    main()
  File "./fuzzer/src/wfuzz.py", line 39, in main
    fuzzer.fuzz()
  File "[...]\Desktop\harbor_new\fuzzer\src\fuzzer.py", line 71, in fuzz
    self._session.fuzz()
  File "[...]\Desktop\harbor_new\env\lib\site-packages\boofuzz\sessions.py", line 608, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "[...]\Desktop\harbor_new\env\lib\site-packages\boofuzz\sessions.py", line 714, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "[...]\Desktop\harbor_new\env\lib\site-packages\boofuzz\sessions.py", line 1447, in _fuzz_current_case
    self._open_connection_keep_trying(target)
  File "[...]\Desktop\harbor_new\env\lib\site-packages\boofuzz\sessions.py", line 1485, in _open_connection_keep_trying
    target.open()
  File "[...]\Desktop\harbor_new\env\lib\site-packages\boofuzz\sessions.py", line 89, in open
    self._target_connection.open()
  File "[...]\Desktop\harbor_new\env\lib\site-packages\boofuzz\socket_connection.py", line 169, in open
    self._sock.connect((self.host, self.port))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

When I run tests from the docker container, the issue seems to be gone.

**Comment by starek4** [comment]
Maybe it can be somehow related to https://github.com/jtpereyda/boofuzz/issues/281 ?

**Comment by jtpereyda** [comment]
Do the sockets get freed after terminating the script?

Can't say if it's related off hand

**Comment by starek4** [comment]
Unfortunately, no. Even after a longer period of time (like ~20 minutes), they all are in state `TimeWait`. I need to restart OS to get rid of them.

**Comment by SR4ven** [comment]
@starek4 could you test if adding `self._sock.shutdown(socket.SHUT_RDWR)` before `close()` fixes the issue?
https://github.com/jtpereyda/boofuzz/blob/e3c79dc0257f10ee4bfaa7273b87d702d3a9d030/boofuzz/socket_connection.py#L116-L125

**Comment by starek4** [comment]
Unfortunately, this does **not** solve the issue. I added `self._sock.shutdown(socket.SHUT_RDWR)` between lines 122 and 123 and I can still reproduce this issue.

**Comment by starek4** [comment]
# Research
I did some research. First of all, this is a valid TCP behavior. This always happens if request are sent so quickly, that we exhaust available sockets resources. So when I create ~15k requests in short of a period of time, this always happen to me. For better understanding of following text I recommend to read article about  `TIME_WAIT` [here](http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html).

# How to solve it
 As we are on client-side, we used ephemeral ports. So setting socket to `SO_REUSEADDR` or `SO_EXCLUSIVEADDRUSE` will **not** help. 

The only thing we can do is to catch `errno.EADDRINUSE`, then try to wait for some period of time and after that, we can try it again.

But, how long to wait? According to [RFC 793](https://tools.ietf.org/html/rfc793), MSL (maximum segment life) should be something about 2 minutes. Microsoft reflects that, so they set up [TcpTimedWaitDelay ](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc938217(v=technet.10)?redirectedfrom=MSDN)for 2 * MSL, so 4 minutes.

So, my suggestion is trying to open a connection up to 4 minutes for `errno.EADDRINUSE` errors. I tested it Windows and WLS and it works great. Is that OK with you, guys (@jtpereyda @SR4ven )? 

I will create a pull request so you can see this in code.

Sources:
- http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html
- https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse
- https://stackoverflow.com/questions/5040491/python-socket-doesnt-close-connection-properly
- https://docs.python.org/2/library/socket.html#socket.socket.shutdown
- https://stackoverflow.com/questions/49928580/python-smtplib-many-sockets-in-time-wait

**Comment by jtpereyda** [comment]
Do you have any recommendations for a future fix with less waiting? From the article you linked, seemed like a few possibilities are:

1. Manually managing a pool of client ports so that SO_REUSEADDR could work.
2. Dynamically switching source IPs -- hacky and really only works with localhost addresses.
3. Reset connections instead of closing them -- could create problems for server?

**Comment by starek4** [comment]
1. This seems to be a good idea, but the implementation could be quite complex. But for the future, it looks like a good solution 👍 . We can create an issue for this as an enhancement and maybe I can look at this after finals.
2. This seems even hackier than workaround with timeouts. I would avoid it.
3. Yeah, as Boofuzz can be used for any server, we do not know if some servers do not accept clients after a few (thousands) reset TCP connections. Well, maybe it is unlikely, but we just do not know for sure.

**Comment by SR4ven** [comment]
@starek4 please don't forget to open an issue about the enhancement you were talking about. 👍
