### ISSUE TITLE
SSL example bugs

### ISSUE THREAD

**Issue by TongweiRen** [jtpereyda/boofuzz#339]
When I run `python fuzz-ssl-server.py` , there is an error:
>Traceback (most recent call last):
  File "fuzz-ssl-server.py", line 22, in <module>
    server_hostname="google.de",
>TypeError: __init__() got an unexpected keyword argument 'server_hostname'

When I run `python fuzz-ssl-client.py` , there is an error:
>Traceback (most recent call last):
  File "fuzz-ssl-client.py", line 18, in <module>
    target=Target(connection=SocketConnection(host="127.0.0.1", port=443, proto="ssl", sslcontext=ctx, server=True))
>TypeError: __init__() got an unexpected keyword argument 'sslcontext'

When I run my own test case, there is an error:
>TypeError: wrap_socket() missing 1 required positional argument: 'sock'
>
And the traceback is:
>Traceback (most recent call last):
  File "SSL_pub_msg_QoS01_Retain1.py", line 56, in <module>
    session.fuzz()
  File "/home/tren/.local/lib/python3.6/site-packages/boofuzz/sessions.py", line 608, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "/home/tren/.local/lib/python3.6/site-packages/boofuzz/sessions.py", line 714, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "/home/tren/.local/lib/python3.6/site-packages/boofuzz/sessions.py", line 1447, in _fuzz_current_case
    self._open_connection_keep_trying(target)
  File "/home/tren/.local/lib/python3.6/site-packages/boofuzz/sessions.py", line 1485, in _open_connection_keep_trying
    target.open()
  File "/home/tren/.local/lib/python3.6/site-packages/boofuzz/sessions.py", line 89, in open
    self._target_connection.open()
  File "/home/tren/.local/lib/python3.6/site-packages/boofuzz/socket_connection.py", line 179, in open
    ssl_sock = ssl.SSLContext.wrap_socket(self._sock)
>TypeError: wrap_socket() missing 1 required positional argument: 'sock'

What should I do to fix them?

**Comment by starek4** [comment]
Hello @TongweiRen ,

I think that the problem is an _old_ version of Boofuzz.

The latest released version of Boofuzz is 0.1.5, which unfortunately does not contain the latest bug fix regarding SSL (https://github.com/jtpereyda/boofuzz/pull/300). 

So you need to install the latest Boofuzz from the source. You can use pip for it!

Firstly, uninstall boofuzz:
`pip uninstall boofuzz`

Then, install it from source:
`pip install git+https://github.com/jtpereyda/boofuzz.git` (you need to have installed `git` client)

**Comment by TongweiRen** [comment]
Yeah, it’s version problem. I just found that using ‘pip install boofuzz –user’ didn't work. Thank you!
