### ISSUE TITLE
No session filename causes crash

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#34]
### Problem
If you don't give Session the `session_filename` attribute, it will crash.
```
$ python ftp.py
Traceback (most recent call last):
  File "ftp.py", line 58, in <module>
    main()
  File "ftp.py", line 11, in main
    session = sessions.Session(sleep_time=0.0, fuzz_data_logger=logger)
  File "/home/joshpere/code/fuzz/boofuzz/boofuzz/sessions.py", line 241, in __init__
    self.import_file()
  File "/home/joshpere/code/fuzz/boofuzz/boofuzz/sessions.py", line 442, in import_file
    with open(self.session_filename, "rb") as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found

```
### Solution
Add a simple check at the beginning of `import_file()`. This is what `export_file()` already does:
````
        if self.session_filename is None:
            return
````

**Comment by jtpereyda** [comment]
Fixed.
