### ISSUE TITLE
Error in handling of exception message

### ISSUE THREAD

**Issue by dorpvom** [jtpereyda/boofuzz#360]
In `socket_connection.py` the block

```python
155|        # Connect is needed only for TCP protocols
156|        elif self.proto == "tcp" or self.proto == "ssl":
157|            try:
158|                self._sock.connect((self.host, self.port))
159|            except socket.error as e:
160|                if e.errno in [errno.ECONNREFUSED, errno.EINPROGRESS]:
161|                    raise exception.BoofuzzTargetConnectionFailedError(e.message)
```
causes an exception on python3 (at least 3.7) in case the caught exception is a `ConnectionRefusedError` since that exception has no attribute `message`.

A quick fix would be:
```python
    raise exception.BoofuzzTargetConnectionFailedError(e.message if hasattr(e, 'message') else str(e))
```

Traceback:

```
[2019-12-09 15:57:05,874]     Info: Web interface can be found at http://localhost:26000
[2019-12-09 15:57:05,943] Test Case: 1: Request.Method.1
[2019-12-09 15:57:05,943]     Info: Type: Group. Default value: b'GET'. Case 1 of 7351 overall.
[2019-12-09 15:57:05,943]     Info: Opening target connection (127.0.0.1:7337)...
[2019-12-09 15:57:05,958]     Error!!!! Unexpected exception! Traceback (most recent call last):
                                File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/socket_connection.py", line 158, in open
                                  self._sock.connect((self.host, self.port))
                              ConnectionRefusedError: [Errno 111] Connection refused
                              
                              During handling of the above exception, another exception occurred:
                              
                              Traceback (most recent call last):
                                File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 703, in _main_fuzz_loop
                                  self._fuzz_current_case(*fuzz_args)
                                File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 1419, in _fuzz_current_case
                                  self._open_connection_keep_trying(target)
                                File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 1457, in _open_connection_keep_trying
                                  target.open()
                                File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 87, in open
                                  self._target_connection.open()
                                File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/socket_connection.py", line 161, in open
                                  raise exception.BoofuzzTargetConnectionFailedError(e.message)
                              AttributeError: 'ConnectionRefusedError' object has no attribute 'message'
                              
Traceback (most recent call last):
  File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/socket_connection.py", line 158, in open
    self._sock.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fuzzer/f_http.py", line 57, in <module>
    sys.exit(fuzz_http())
  File "fuzzer/f_http.py", line 51, in fuzz_http
    session.fuzz()
  File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 598, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 703, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 1419, in _fuzz_current_case
    self._open_connection_keep_trying(target)
  File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 1457, in _open_connection_keep_trying
    target.open()
  File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/sessions.py", line 87, in open
    self._target_connection.open()
  File "/tmp/.env3/lib/python3.7/site-packages/boofuzz/socket_connection.py", line 161, in open
    raise exception.BoofuzzTargetConnectionFailedError(e.message)
AttributeError: 'ConnectionRefusedError' object has no attribute 'message'

```

**Comment by dorpvom** [comment]
Nevermind, saw it was fixed since latest release

**Comment by SR4ven** [comment]
Glad to hear that this is no longer an issue, I was just about to push a release!

Anyway, thanks for reporting @dorpvom!

**Comment by jtpereyda** [comment]
Thank you @dorpvom and @SR4ven
