### ISSUE TITLE
BER lego broken

### ISSUE THREAD

**Issue by SR4ven** [jtpereyda/boofuzz#395]
Code to reproduce:
```python
from boofuzz import *

s_initialize("Test")
s_lego("ber_string", value="testval")

sess = Session(
    target=Target(connection=SocketConnection("127.0.0.1", 80, proto="tcp")),
)
sess.connect(s_get("Test"))
sess.fuzz()
```
Traceback
```python
Traceback (most recent call last):
  File "/snap/pycharm-professional/183/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/dev/Documents/boofuzz_requests/dev.py", line 102, in <module>
    fuzz()
  File "/home/dev/Documents/boofuzz_requests/dev.py", line 98, in fuzz
    sess.fuzz()
  File "/home/dev/PycharmProjects/boofuzz/boofuzz/sessions.py", line 635, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "/home/dev/PycharmProjects/boofuzz/boofuzz/sessions.py", line 741, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "/home/dev/PycharmProjects/boofuzz/boofuzz/sessions.py", line 1480, in _fuzz_current_case
    repr(self.fuzz_node.mutant.original_value),
  File "/home/dev/PycharmProjects/boofuzz/boofuzz/blocks/size.py", line 105, in original_value
    length = self._original_calculated_length()
  File "/home/dev/PycharmProjects/boofuzz/boofuzz/blocks/size.py", line 109, in _original_calculated_length
    return self.offset + self._inclusive_length_of_self + self._original_length_of_target_block
  File "/home/dev/PycharmProjects/boofuzz/boofuzz/blocks/size.py", line 11, in safe_recurse
    result = f(self, *args, **kwargs)
  File "/home/dev/PycharmProjects/boofuzz/boofuzz/blocks/size.py", line 209, in _original_length_of_target_block
    length = len(self.request.names[self.block_name].original_value)
KeyError: 'LEGO_00000000_STR'
```

#155 might be related

**Comment by erik-smit** [comment]
ber.py does: 
```
        str_block = blocks.Block(name + "_STR", request)
        str_block.push(primitives.String(self.value))

        self.push(blocks.Size(name + "_STR", request, endian=BIG_ENDIAN, fuzzable=True))
        self.push(str_block)
```

Creates Block with String primitive with name + "_STR" and Size block that looks at name + "_STR" and adds them to self.stack.
However, Size looks at self.request.names which only contains the original name, not the subblocks made by ber_string.

**Comment by SR4ven** [comment]
Thanks for looking into this @erik-smit!

For now I wouldn't recommend putting too much effort into fixing this before #422 is merged.

After #422 is merged we should take a look at this again and evaluate how much work we have to put into a fix.
I haven't used ber myself, and I have no idea how many people use it. Probably not too many if it's been broken for so long.
