### ISSUE TITLE
Cannot run, crashes

### ISSUE THREAD

**Issue by FFrozTT** [jtpereyda/boofuzz#410]
Up-to-date Win 10 machine. Just installed Python3.8.2, pip, setuptools, winpcap. Followed guide.  Setup.py install runs fine then this:

```
(env) C:\Boofuzz>python network_monitor.py
Traceback (most recent call last):
  File "network_monitor.py", line 13, in <module>
    import pcapy  # pytype: disable=import-error
ModuleNotFoundError: No module named 'pcapy'
```

Try to install pcapy through pip:
```
(env) C:\Boofuzz>pip3 install pcapy
Collecting pcapy
  Using cached pcapy-0.11.4.tar.gz (37 kB)
Installing collected packages: pcapy
    Running setup.py install for pcapy ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-install-d9u__v51\\pcapy\\setup.py'"'"'; __file__='"'"'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-install-d9u__v51\\pcapy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\myuser\AppData\Local\Temp\pip-record-33d9so_5\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\env\include\site\python3.8\pcapy'
         cwd: C:\Users\myuser\AppData\Local\Temp\pip-install-d9u__v51\pcapy\
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'pcapy' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\win32
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -Ic:\wpdpack\Include -Ic:\env\include -IC:\Python\Python38\include -IC:\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tppcapdumper.cc /Fobuild\temp.win-amd64-3.8\Release\pcapdumper.obj
    pcapdumper.cc
    pcapdumper.cc(11): fatal error C1083: Cannot open include file: 'pcap.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-install-d9u__v51\\pcapy\\setup.py'"'"'; __file__='"'"'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-install-d9u__v51\\pcapy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\myuser\AppData\Local\Temp\pip-record-33d9so_5\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\env\include\site\python3.8\pcapy' Check the logs for full command output.
```

Try to install pcapy from source:

```
(env) C:\pcapy-0.11.5>python setup.py install
C:\env\lib\site-packages\setuptools\dist.py:471: UserWarning: Normalizing '0.11.5-dev' to '0.11.5.dev0'
  warnings.warn(
running install
running bdist_egg
running egg_info
writing pcapy.egg-info\PKG-INFO
writing dependency_links to pcapy.egg-info\dependency_links.txt
writing top-level names to pcapy.egg-info\top_level.txt
C:\pcapy-0.11.5\WpdPack_4_1_2\WpdPack\Include\bittypes.h(124): note: see previous definition of 'PRIx64'
pcapy.cc(262): error C2375: 'PyInit_pcapy': redefinition; different linkage
C:\pcapy-0.11.5\pcapy.h(23): note: see declaration of 'PyInit_pcapy'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

I've tried running from cmd, VS2008 cmd, VS2017 cmd, VS2019 cmd, all 32 and 64 bit versions.

**Comment by FFrozTT** [comment]
I found a workaround for the pcapy problem by downloading the [WinPCAP developers pack](https://www.winpcap.org/devel.htm) and running:

`pip install pcapy  --global-option="build_ext" --global-option="-IC:\pcapy-0.11.5\WpdPack_4_1_2\WpdPack\include" --global-option="-LC:\pcapy-0.11.5\WpdPack_4_1_2\WpdPack\Lib"`

But now I just get this error.

```
(env) C:\Boofuzz>python network_monitor.py
C:\Boofuzz\boofuzz\__init__.py:30: UserWarning: Importing curses failed. Console GUI features will not be available.
  from .fuzz_logger_curses import FuzzLoggerCurses
Traceback (most recent call last):
  File "network_monitor.py", line 293, in <module>
    main()
  File "network_monitor.py", line 250, in main
    usage_message = create_usage(ifs)
  File "network_monitor.py", line 63, in create_usage
    import _winreg  # pytype: disable=import-error
ModuleNotFoundError: No module named '_winreg'
```

So I edited the file network_monitor.py and replaced all occurrences of the word "_winreg" with "winreg" and I think maybe it's working now but I get this warning every time:

```
C:\Boofuzz\boofuzz\__init__.py:30: UserWarning: Importing curses failed. Console GUI features will not be available.
  from .fuzz_logger_curses import FuzzLoggerCurses
```
Hopefully someone else finds this information because this was 2-3 hours of hair pulling.

**Comment by SR4ven** [comment]
Thank you for sharing your problem and solution @FFrozTT!

The first error is related to pcapy, which we didn't list as a requirement for boofuzz. Currently only the (more or less deprecated) network monitor requires it and as you already noticed, installing can be problematic.
I'll open a PR that adds a note about this extra requirement to the installation docs.

The second error you got, about `winreg` is a Python 2/3 compatibility issue as the module was renamed in Python 3. I'll add a fix for that to the PR I mentioned. Thanks for pointing this out!

The UserWarning you're getting is about the curses console GUI, which is not supported on Windows yet. As this a completely optional feature, you can safely ignore the warning.
