### ISSUE TITLE
Silent TypeError in test_socket_connection

### ISSUE THREAD

**Issue by SR4ven** [jtpereyda/boofuzz#456]
While running the unittests I noticed the following error. It's thrown by a different thread so pytest doesn't fail.

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dev/PycharmProjects/boofuzz/unit_tests/test_socket_connection.py", line 243, in receive_until
    self.server_socket.sendto(self.data_to_send, addr)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by SR4ven** [comment]
Problem is no longer present.
