### ISSUE TITLE
AttributeError: 'ProcessMonitorPedrpcServer' object has no attribute 'set_options'

### ISSUE THREAD

**Issue by mauriciogalindo** [jtpereyda/boofuzz#478]
Hi Team,

I am receiving the following error below any help is appreciate.

Thank you.

C:\boofuzz>python process_monitor.py -c KSTET_CRASH -l 5 -p vulnserver.exe -P 26002
C:\boofuzz\boofuzz\fuzz_logger_curses.py:14: UserWarning: Importing curses failed. Optional console GUI features will not be available.
  warnings.warn("Importing curses failed. Optional console GUI features will not be available.", UserWarning)
[11:28.33] Process Monitor PED-RPC server initialized:
[11:28.33]       listening on:  0.0.0.0:26002
[11:28.33]       crash file:    C:\boofuzz\KSTET_CRASH
[11:28.33]       # records:     0
[11:28.33]       proc name:     vulnserver.exe
[11:28.33]       log level:     5
[11:28.33] awaiting requests...
PED-RPC> remote method "set_options" of <boofuzz.utils.process_monitor_pedrpc_server.ProcessMonitorPedrpcServer object at 0x03EBE810> cannot be f
ound
Traceback (most recent call last):
  File "process_monitor.py", line 66, in <module>
    go()
  File "C:\Python27\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "process_monitor.py", line 62, in go
    serve_procmon(port=port, crash_bin=crash_bin, proc_name=proc_name, ignore_pid=ignore_pid, log_level=log_level)
  File "process_monitor.py", line 22, in serve_procmon
    servlet.serve_forever()
  File "C:\boofuzz\boofuzz\monitors\pedrpc.py", line 343, in serve_forever
    method = getattr(self, method_name)
AttributeError: 'ProcessMonitorPedrpcServer' object has no attribute 'set_options'

=====================================================================
script I am using to fuzz.

from boofuzz import *

def main():
    f = open('ftp-fuzz.csv','wb')

    target_ip = "192.168.132.129"
    session = Session (
        target=Target(
            connection=SocketConnection(target_ip,9999, proto='tcp'),
            procmon=pedrpc.Client(target_ip,26002),
            procmon_options={"proc_name" : "vulnserver.exe", "stop_commands": ['wmic process where (name="vulnserver") delete'], "start_commands": ['C:\\vulnserver\\vulnserver.exe']}
        ),
        sleep_time=1,
        fuzz_loggers=[FuzzLoggerText(),FuzzLoggerCsv(file_handle=f)]
        )

    s_initialize("kstet")
    s_static("KSTET")
    s_delim(" ",fuzzable=False)
    s_string("test")
    s_static("\r\n")

    session.connect(s_get("kstet"))

    session.fuzz()

if __name__=="__main__":
    main()

**Comment by weechen** [comment]
There's an update to how to use procmon. Based on how the new style goes, your code should be:

```
from boofuzz import *

def main():
f = open('ftp-fuzz.csv','wb')

target_ip = "192.168.132.129"

options = {"proc_name" : "vulnserver.exe", "stop_commands": ['wmic process where (name="vulnserver") delete'], "start_commands": ['C:\\vulnserver\\vulnserver.exe']}
procmon = ProcessMonitor(target_ip,26002)
procmon.set_options(**options)
monitors = [procmon]

session = Session (
    target=Target(
        connection=SocketConnection(target_ip,9999, proto='tcp'),
        monitors=monitors
    ),
    sleep_time=1,
    fuzz_loggers=[FuzzLoggerText(),FuzzLoggerCsv(file_handle=f)]
    )

s_initialize("kstet")
s_static("KSTET")
s_delim(" ",fuzzable=False)
s_string("test")
s_static("\r\n")

session.connect(s_get("kstet"))

session.fuzz()
```

You can refer to [this script](https://github.com/jtpereyda/boofuzz-ftp/blob/master/ftp.py) on how to use procmon.

**Comment by jtpereyda** [comment]
Thanks @mauriciogalindo & @weechen for the question and answer.
I think we still need an example like this in the docs.
