### ISSUE TITLE
How to use s_from_file()?It will cause some errors

### ISSUE THREAD

**Issue by donothingme** [jtpereyda/boofuzz#613]
### Discussed in https://github.com/jtpereyda/boofuzz/discussions/612

<div type='discussions-op-text'>

<sup>Originally posted by **donothingme** March 24, 2022</sup>
When I call s_from_file() more than once in one block, it will cause a error. However, if i only call s_from_file() once, it will have no errors.
So I want to know how to use s_from_file()? Thank you!

I have a protocal definition like follows:

```
from boofuzz import *

s_initialize(name='cgi')
with s_block("Request-Line"):
    s_static("POST /a.cgi HTTP/1.1\r\n")
    s_static("Host: 192.168.0.1\r\n", name="Host")
    s_static("Proxy-Connection: keep-alive\r\n", name="Proxy-Connection")
    s_static("Content-Length: ", name="Content-Length")
    s_size("Data", output_format="ascii", fuzzable=False)
    s_static("\r\n", name="Content-Length-end")
    s_static("Accept: text/plain, */*; q=0.01\r\n", name="Accept")
    s_static("X-Requested-With: XMLHttpRequest\r\n", name="X-Requested-With")
    s_static("User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36\r\n", name="User-Agent")
    s_static("Content-Type: application/x-www-form-urlencoded; charset=UTF-8\r\n", name="Content-Type")
    s_static("Origin: http://192.168.0.1\r\n", name="Origin")
    s_static("Referer: http://192.168.0.1/sysManage/sysTool.html?5385262951\r\n", name="Referer")
    s_static("Accept-Encoding: gzip, deflate\r\n", name="Accept-Encoding")
    s_static("Accept-Language: zh-CN,zh;q=0.9\r\n", name="Accept-Language")
    s_static("Cookie: _:USERNAME:_=; G3v3_user=\r\n", name="Cookie")
    s_static("\r\n")

with s_block("Data"):
    s_static("packageNum=", name="packageNum")
    s_from_file(filename='./fuzz_string.txt', encoding='ascii', name='packageNum_from_file')
    s_static("&", name="packageNum_test")

# with s_block("data2"):
    s_static("hostName=", name="hostName")
    s_from_file(filename='./fuzz_string.txt', encoding='ascii', name='hostName_from_file')
    s_static("&", name="hostName_test")
    
    s_static("packageSize=", name="packageSize")
    s_from_file(filename='./fuzz_string.txt', encoding='u8', name='packageSize_from_file')
    s_static("&", name="packageSize_test")
    
    s_static("\r\n")
    s_static("\r\n")

session = Session(target=Target(
    connection=TCPSocketConnection('192.168.0.1', 80)
),
    ignore_connection_reset=True,
    ignore_connection_aborted=True,
)  # pre_send_callbacks=[pre_callback]  # TODO

session.connect(s_get('cgi'))
session.fuzz()
```

and it will report a error:

```
[2022-03-24 11:07:37,570]     Info: Web interface can be found at http://localhost:26001
[2022-03-24 11:07:37,571] Test Case: 1: cgi:[cgi.Data.packageNum_from_file:0]
[2022-03-24 11:07:37,571]     Info: Type: FromFile
[2022-03-24 11:07:37,571]     Info: Opening target connection (192.168.0.1:80)...
[2022-03-24 11:07:37,595]     Info: Connection opened.
[2022-03-24 11:07:37,595]   Test Step: Monitor CallbackMonitor#1653356311120[pre=[],post=[],restart=[],post_start_target=[]].pre_send()
[2022-03-24 11:07:37,595]   Test Step: Fuzzing Node 'cgi'
Traceback (most recent call last):
  File "fuzz.py", line 61, in <module>
    session.fuzz()
  File "\lib\site-packages\boofuzz\sessions.py", line 1264, in fuzz
    self._main_fuzz_loop(self._generate_mutations_indefinitely(max_depth=max_depth))
  File "\lib\site-packages\boofuzz\sessions.py", line 1388, in _main_fuzz_loop
    self._fuzz_current_case(mutation_context)
  File "\lib\site-packages\boofuzz\sessions.py", line 1754, in _fuzz_current_case
    self.transmit_fuzz(
  File "\lib\site-packages\boofuzz\sessions.py", line 1166, in transmit_fuzz
    data = self.fuzz_node.render(mutation_context)
  File "\lib\site-packages\boofuzz\blocks\request.py", line 130, in render
    return self.get_child_data(mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\fuzzable_block.py", line 71, in get_child_data
    rendered += item.render(mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\fuzzable.py", line 154, in render
    return self.encode(value=self.get_value(mutation_context=mutation_context), mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\blocks\block.py", line 114, in encode
    child_data = super(Block, self).get_child_data(mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\fuzzable_block.py", line 71, in get_child_data
    rendered += item.render(mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\fuzzable.py", line 154, in render
    return self.encode(value=self.get_value(mutation_context=mutation_context), mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\blocks\size.py", line 112, in encode
    self._length_to_bytes(self._calculated_length(mutation_context=mutation_context))
  File "lib\site-packages\boofuzz\blocks\size.py", line 124, in _calculated_length
    + self._length_of_target_block(mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\blocks\size.py", line 11, in safe_recurse
    result = f(self, *args, **kwargs)
  File "\lib\site-packages\boofuzz\blocks\size.py", line 149, in _length_of_target_block
    return len(target_block.render(mutation_context=mutation_context))
  File "\lib\site-packages\boofuzz\fuzzable.py", line 154, in render
    return self.encode(value=self.get_value(mutation_context=mutation_context), mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\blocks\block.py", line 114, in encode
    child_data = super(Block, self).get_child_data(mutation_context=mutation_context)
  File "\lib\site-packages\boofuzz\fuzzable_block.py", line 71, in get_child_data
    rendered += item.render(mutation_context=mutation_context)
TypeError: can't concat str to bytes
[2022-03-24 11:07:37,764]     Error!!!! Unexpected exception! Traceback (most recent call last):
                                File " \lib\site-packages\boofuzz\sessions.py", line 1388, in _main_fuzz_loop
                                  self._fuzz_current_case(mutation_context)
                                File " \lib\site-packages\boofuzz\sessions.py", line 1754, in _fuzz_current_case
                                  self.transmit_fuzz(
                                File " \lib\site-packages\boofuzz\sessions.py", line 1166, in transmit_fuzz
                                  data = self.fuzz_node.render(mutation_context)
                                File " \lib\site-packages\boofuzz\blocks\request.py", line 130, in render
                                  return self.get_child_data(mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\fuzzable_block.py", line 71, in get_child_data
                                  rendered += item.render(mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\fuzzable.py", line 154, in render
                                  return self.encode(value=self.get_value(mutation_context=mutation_context), mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\blocks\block.py", line 114, in encode
                                  child_data = super(Block, self).get_child_data(mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\fuzzable_block.py", line 71, in get_child_data
                                  rendered += item.render(mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\fuzzable.py", line 154, in render
                                  return self.encode(value=self.get_value(mutation_context=mutation_context), mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\blocks\size.py", line 112, in encode
                                  self._length_to_bytes(self._calculated_length(mutation_context=mutation_context))
                                File " \lib\site-packages\boofuzz\blocks\size.py", line 124, in _calculated_length
                                  + self._length_of_target_block(mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\blocks\size.py", line 11, in safe_recurse
                                  result = f(self, *args, **kwargs)
                                File " \lib\site-packages\boofuzz\blocks\size.py", line 149, in _length_of_target_block
                                  return len(target_block.render(mutation_context=mutation_context))
                                File " \lib\site-packages\boofuzz\fuzzable.py", line 154, in render
                                  return self.encode(value=self.get_value(mutation_context=mutation_context), mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\blocks\block.py", line 114, in encode
                                  child_data = super(Block, self).get_child_data(mutation_context=mutation_context)
                                File " \lib\site-packages\boofuzz\fuzzable_block.py", line 71, in get_child_data
                                  rendered += item.render(mutation_context=mutation_context)
                              TypeError: can't concat str to bytes
                              

Process finished with exit code 1

```
</div>

**Comment by jtpereyda** [comment]
Hi @donothingme ! Thanks for opening an issue. It seems like you may have found a bug in `s_from_file`. It's interesting that you say it only happens when using it twice. Here is one idea -- what if you try changing the filename of the second `s_from_file`, so that they are not pointing at the same exact file?

It may take some proper debugging to trace the root cause though.

**Comment by SR4ven** [comment]
The problem here was the type of the `default_value` which is string, but `FromFile` doesn't provide an `encode` method.

I've opened a PR that changes the type of the `default_value` to bytes. Would be nice if you could verify that it solves your problem @donothingme.

About this happening with more than one FromFile, that might be because the default_value will not be used if the primitive is being actively mutated. So the first FromFile might be mutated and is fine while the second one uses it's default_value which causes the exception.
